const mongoose = require("mongoose");
const Felines = require("./models/felines");
const Comment = require("./models/comments");

const data = [
  {name: "Penny", image: "https://images.unsplash.com/photo-1479623186097-2bb07e242ae0?ixlib=rb-0.3.5&ixid=eyJhcHBfaWQiOjEyMDd9&s=8a1f1879d128d8d7eefcb80679d0362d&auto=format&fit=crop&w=800&q=60", description: "Be a nyan cat, feel great about it, be annoying 24/7 poop rainbows in litter box all day throw down all the stuff in the kitchen, i'm going to lap some water out of my master's cup meow rub face on owner so flee in terror at cucumber discovered on floor yet try to hold own back foot to clean it but foot reflexively kicks you in face, go into a rage and bite own foot, hard.", age: "1 Year Old", breed: "British Shorthair", author: "Brandon"},
  {name: "Kitty", image: "https://images.unsplash.com/photo-1500174857981-b769ffdc53ce?ixlib=rb-0.3.5&ixid=eyJhcHBfaWQiOjEyMDd9&s=cf95402da5505a437d9579957e3da6be&auto=format&fit=crop&w=800&q=60", description: "Be a nyan cat, feel great about it, be annoying 24/7 poop rainbows in litter box all day throw down all the stuff in the kitchen, i'm going to lap some water out of my master's cup meow rub face on owner so flee in terror at cucumber discovered on floor yet try to hold own back foot to clean it but foot reflexively kicks you in face, go into a rage and bite own foot, hard.", age: "2 Years Old", breed: "Persian"},
  {name: "Rex", image: "https://images.unsplash.com/photo-1516750105099-4b8a83e217ee?ixlib=rb-0.3.5&ixid=eyJhcHBfaWQiOjEyMDd9&s=e48de5e9fe35555adb46880490f1bb28&auto=format&fit=crop&w=800&q=60", description: "Be a nyan cat, feel great about it, be annoying 24/7 poop rainbows in litter box all day throw down all the stuff in the kitchen, i'm going to lap some water out of my master's cup meow rub face on owner so flee in terror at cucumber discovered on floor yet try to hold own back foot to clean it but foot reflexively kicks you in face, go into a rage and bite own foot, hard.", age: "3 Years Old", breed: "Ragdoll"},
  {name: "Max", image: "https://images.unsplash.com/photo-1486865971567-61bc1066d6e5?ixlib=rb-0.3.5&ixid=eyJhcHBfaWQiOjEyMDd9&s=0acda4c559d71afd4e0caf91a42bce3d&auto=format&fit=crop&w=800&q=60", description: "Be a nyan cat, feel great about it, be annoying 24/7 poop rainbows in litter box all day throw down all the stuff in the kitchen, i'm going to lap some water out of my master's cup meow rub face on owner so flee in terror at cucumber discovered on floor yet try to hold own back foot to clean it but foot reflexively kicks you in face, go into a rage and bite own foot, hard.", age: "1 Year Old", breed: "Maine Coon"},
  {name: "Marty", image: "https://images.unsplash.com/photo-1486431674253-40659df26e5e?ixlib=rb-0.3.5&ixid=eyJhcHBfaWQiOjEyMDd9&s=21dfbc26147ed4ebcd759844a3ca8c79&auto=format&fit=crop&w=800&q=60", description: "Be a nyan cat, feel great about it, be annoying 24/7 poop rainbows in litter box all day throw down all the stuff in the kitchen, i'm going to lap some water out of my master's cup meow rub face on owner so flee in terror at cucumber discovered on floor yet try to hold own back foot to clean it but foot reflexively kicks you in face, go into a rage and bite own foot, hard.", age: "2 Years Old", breed: "Bengal"},
  {name: "Luna", image: "https://images.unsplash.com/photo-1507759138407-297a0785033e?ixlib=rb-0.3.5&ixid=eyJhcHBfaWQiOjEyMDd9&s=efce98679229fb7f1cfb28a93fab3942&auto=format&fit=crop&w=800&q=60", description: "Be a nyan cat, feel great about it, be annoying 24/7 poop rainbows in litter box all day throw down all the stuff in the kitchen, i'm going to lap some water out of my master's cup meow rub face on owner so flee in terror at cucumber discovered on floor yet try to hold own back foot to clean it but foot reflexively kicks you in face, go into a rage and bite own foot, hard.", age: "3 Years Old", breed: "Abyssinian"},
  {name: "Abby", image: "https://images.unsplash.com/photo-1515172486498-7a0b147a16c5?ixlib=rb-0.3.5&ixid=eyJhcHBfaWQiOjEyMDd9&s=7213a9dd9c60b6f950a47acc83a71e8a&auto=format&fit=crop&w=800&q=60", description: "Be a nyan cat, feel great about it, be annoying 24/7 poop rainbows in litter box all day throw down all the stuff in the kitchen, i'm going to lap some water out of my master's cup meow rub face on owner so flee in terror at cucumber discovered on floor yet try to hold own back foot to clean it but foot reflexively kicks you in face, go into a rage and bite own foot, hard.", age: "4 Years Old", breed: "Russian Blue"},
  {name: "Nala", image: "https://images.unsplash.com/photo-1508686546564-a142a9b633ba?ixlib=rb-0.3.5&ixid=eyJhcHBfaWQiOjEyMDd9&s=677c7d6d38b7c36e061a1769285914d2&auto=format&fit=crop&w=800&q=60", description: "Be a nyan cat, feel great about it, be annoying 24/7 poop rainbows in litter box all day throw down all the stuff in the kitchen, i'm going to lap some water out of my master's cup meow rub face on owner so flee in terror at cucumber discovered on floor yet try to hold own back foot to clean it but foot reflexively kicks you in face, go into a rage and bite own foot, hard.", age: "2 Years Old", breed: "Burmese"},
  {name: "Bell", image: "https://images.unsplash.com/photo-1512027792141-80e5842b87c8?ixlib=rb-0.3.5&ixid=eyJhcHBfaWQiOjEyMDd9&s=00176178041b755cde5fc351b5c1c605&auto=format&fit=crop&w=800&q=60", description: "Be a nyan cat, feel great about it, be annoying 24/7 poop rainbows in litter box all day throw down all the stuff in the kitchen, i'm going to lap some water out of my master's cup meow rub face on owner so flee in terror at cucumber discovered on floor yet try to hold own back foot to clean it but foot reflexively kicks you in face, go into a rage and bite own foot, hard.", age: "1 Year Old", breed: "American Bobtail"},
  {name: "Daisy", image: "https://images.unsplash.com/photo-1509123779391-4a82c1c0264f?ixlib=rb-0.3.5&ixid=eyJhcHBfaWQiOjEyMDd9&s=1b62964a957e9092625e586acb27fc12&auto=format&fit=crop&w=800&q=60", description: "Be a nyan cat, feel great about it, be annoying 24/7 poop rainbows in litter box all day throw down all the stuff in the kitchen, i'm going to lap some water out of my master's cup meow rub face on owner so flee in terror at cucumber discovered on floor yet try to hold own back foot to clean it but foot reflexively kicks you in face, go into a rage and bite own foot, hard.", age: "5 Years Old", breed: "Exotic Shorthair"},
  {name: "Tiger", image: "https://images.unsplash.com/photo-1507984211203-76701d7bb120?ixlib=rb-0.3.5&ixid=eyJhcHBfaWQiOjEyMDd9&s=eacbf50fac29a13afba26ad7499cedee&auto=format&fit=crop&w=800&q=60", description: "Be a nyan cat, feel great about it, be annoying 24/7 poop rainbows in litter box all day throw down all the stuff in the kitchen, i'm going to lap some water out of my master's cup meow rub face on owner so flee in terror at cucumber discovered on floor yet try to hold own back foot to clean it but foot reflexively kicks you in face, go into a rage and bite own foot, hard.", age: "6 Years Old", breed: "American Shorthair"},
  {name: "Milo", image: "https://images.unsplash.com/photo-1463008420065-8274332e2be8?ixlib=rb-0.3.5&ixid=eyJhcHBfaWQiOjEyMDd9&s=4e604c4145ad16878f99be2fb31ff25c&auto=format&fit=crop&w=800&q=60", description: "Be a nyan cat, feel great about it, be annoying 24/7 poop rainbows in litter box all day throw down all the stuff in the kitchen, i'm going to lap some water out of my master's cup meow rub face on owner so flee in terror at cucumber discovered on floor yet try to hold own back foot to clean it but foot reflexively kicks you in face, go into a rage and bite own foot, hard.", age: "6 Years Old", breed: "Scottish Fold"},
  {name: "Simba", image: "https://images.unsplash.com/photo-1517330218601-cd55b21a35af?ixlib=rb-0.3.5&ixid=eyJhcHBfaWQiOjEyMDd9&s=bbbb06e59bcd6ced8b5b10483eaba117&auto=format&fit=crop&w=800&q=60", description: "Be a nyan cat, feel great about it, be annoying 24/7 poop rainbows in litter box all day throw down all the stuff in the kitchen, i'm going to lap some water out of my master's cup meow rub face on owner so flee in terror at cucumber discovered on floor yet try to hold own back foot to clean it but foot reflexively kicks you in face, go into a rage and bite own foot, hard.", age: "7 Years Old", breed: "Siberian"},
  {name: "Oreo", image: "https://images.unsplash.com/photo-1515328892697-f417170263ce?ixlib=rb-0.3.5&ixid=eyJhcHBfaWQiOjEyMDd9&s=0107ac2162dbcc8530fe1d7a76d47bea&auto=format&fit=crop&w=800&q=60", description: "Be a nyan cat, feel great about it, be annoying 24/7 poop rainbows in litter box all day throw down all the stuff in the kitchen, i'm going to lap some water out of my master's cup meow rub face on owner so flee in terror at cucumber discovered on floor yet try to hold own back foot to clean it but foot reflexively kicks you in face, go into a rage and bite own foot, hard.", age: "2 Years Old", breed: "Siamese"},
  {name: "Sam", image: "https://images.unsplash.com/photo-1509228552759-5ff5395178ae?ixlib=rb-0.3.5&ixid=eyJhcHBfaWQiOjEyMDd9&s=08f25add18176508ef3ff052dba36fa4&auto=format&fit=crop&w=800&q=60", description: "Be a nyan cat, feel great about it, be annoying 24/7 poop rainbows in litter box all day throw down all the stuff in the kitchen, i'm going to lap some water out of my master's cup meow rub face on owner so flee in terror at cucumber discovered on floor yet try to hold own back foot to clean it but foot reflexively kicks you in face, go into a rage and bite own foot, hard.", age: "3 Years Old", breed: "Birman"},
  {name: "Misty", image: "https://images.unsplash.com/photo-1517916204339-692163c306be?ixlib=rb-0.3.5&ixid=eyJhcHBfaWQiOjEyMDd9&s=e9aff3551472bdd91829f0c596579e96&auto=format&fit=crop&w=800&q=60", description: "Be a nyan cat, feel great about it, be annoying 24/7 poop rainbows in litter box all day throw down all the stuff in the kitchen, i'm going to lap some water out of my master's cup meow rub face on owner so flee in terror at cucumber discovered on floor yet try to hold own back foot to clean it but foot reflexively kicks you in face, go into a rage and bite own foot, hard.", age: "1 Year Old", breed: "Cornish Rex"},
  {name: "Coco", image: "https://images.unsplash.com/photo-1503386435953-66943ba30817?ixlib=rb-0.3.5&ixid=eyJhcHBfaWQiOjEyMDd9&s=d414b847aa83183d064683258a95232a&auto=format&fit=crop&w=800&q=60", description: "Be a nyan cat, feel great about it, be annoying 24/7 poop rainbows in litter box all day throw down all the stuff in the kitchen, i'm going to lap some water out of my master's cup meow rub face on owner so flee in terror at cucumber discovered on floor yet try to hold own back foot to clean it but foot reflexively kicks you in face, go into a rage and bite own foot, hard.", age: "5 Years Old", breed: "Tonkinese"}
]

function seedDB(){
  // Remove Camgrounds...
  Felines.remove({}, function(err){
    if(err){
      console.log(err);
    }
    console.log("Removed felines");
    // Add Campgrounds..
    data.forEach(function(seed){
      Felines.create(seed, function(err, felines){
        if(err){
          console.log(err)
        } else {
          console.log("Added felines");
          // Adding comments...
          // Comment.create(
          //   {text: "This place is great!", author.username: "Brandon"}, function(err, comment){
          //     if(err){
          //       console.log(err);
          //     } else {
          //       felines.comments.push(comment);
          //       felines.save();
          //       console.log("Created new comment");
          //     }
          //   }
          // )
        }
      });
    })
  });
}

module.exports = seedDB;